#!/usr/bin/env bash
set -eu

# Lists the current directory's files in Vim, so you can edit it and save to rename them
# USAGE: vimv [file1 file2]
# https://github.com/thameera/vimv

declare -r FILENAMES_FILE=$(mktemp "${TMPDIR:-/tmp}/vimv.XXX")

trap '{ rm -f "${FILENAMES_FILE}" ; }' EXIT

if [ $# -ne 0 ]; then
    src=( "$@" )
else
    IFS=$'\r\n' GLOBIGNORE='*' command eval 'src=($(ls))'
fi

for ((i=0;i<${#src[@]};++i)); do
    echo "${src[i]}" >> "${FILENAMES_FILE}"
done

${EDITOR:-vi} "${FILENAMES_FILE}"

IFS=$'\r\n' GLOBIGNORE='*' command eval 'dest=($(cat "${FILENAMES_FILE}"))'

if (( ${#src[@]} != ${#dest[@]} )); then
    echo "WARN: Number of files changed. Did you delete a line by accident? Aborting.." >&2
    exit 1
fi

declare -i desired_renames=0
for ((i=0;i<${#src[@]};++i)); do
    if [ "${src[i]}" != "${dest[i]}" ]; then
        ((++desired_renames))
    fi
done

declare -i fruitless_attempts=0
declare -i old_count=0
declare -i count=0
while [ "$fruitless_attempts" -lt 2 ] && [ "$count" != "$desired_renames" ]; do
    for ((i=0;i<${#src[@]};++i)); do
        if [ "${src[i]}" != "${dest[i]}" ]; then
            if [ ! -e "${dest[i]}" ]; then
                mkdir -p "$(dirname "${dest[i]}")"
                if git ls-files --error-unmatch "${src[i]}" > /dev/null 2>&1; then
                    git mv "${src[i]}" "${dest[i]}"
                else
                    mv -n "${src[i]}" "${dest[i]}"
                fi
                ((++count))
            else
                continue
            fi
        fi
    done
    if [ "$count" != "$old_count" ]; then
        ((old_count=count))
    else
        ((++fruitless_attempts))
    fi
done

echo "$count" files renamed.
